# Form implementation generated from reading ui file 'c:\Users\Said\Desktop\HP QT\GUI\Ajustes.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Ajustes(object):
    def setupUi(self, Ajustes):
        Ajustes.setObjectName("Ajustes")
        Ajustes.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Ajustes.resize(674, 433)
        self.label = QtWidgets.QLabel(parent=Ajustes)
        self.label.setGeometry(QtCore.QRect(-2, -5, 681, 441))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\Said\\Desktop\\HP QT\\GUI\\../imagen/ajustes.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.ant = QtWidgets.QPushButton(parent=Ajustes)
        self.ant.setGeometry(QtCore.QRect(8, 344, 67, 83))
        self.ant.setAutoFillBackground(False)
        self.ant.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Said\\Desktop\\HP QT\\GUI\\../imagen/regreso.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ant.setIcon(icon)
        self.ant.setIconSize(QtCore.QSize(260, 80))
        self.ant.setDefault(False)
        self.ant.setFlat(True)
        self.ant.setObjectName("ant")
        self.continuar = QtWidgets.QPushButton(parent=Ajustes)
        self.continuar.setGeometry(QtCore.QRect(192, 340, 245, 84))
        self.continuar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.continuar.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.continuar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Said\\Desktop\\HP QT\\GUI\\../imagen/cont.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.continuar.setIcon(icon1)
        self.continuar.setIconSize(QtCore.QSize(400, 300))
        self.continuar.setAutoDefault(True)
        self.continuar.setFlat(True)
        self.continuar.setObjectName("continuar")

        self.retranslateUi(Ajustes)
        QtCore.QMetaObject.connectSlotsByName(Ajustes)

    def retranslateUi(self, Ajustes):
        _translate = QtCore.QCoreApplication.translate
        Ajustes.setWindowTitle(_translate("Ajustes", "Ajustes"))
