# Form implementation generated from reading ui file 'c:\Users\Said\Desktop\HP QT\GUI\Calen.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Calendario(object):
    def setupUi(self, Calendario):
        Calendario.setObjectName("Calendario")
        Calendario.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Calendario.resize(795, 692)
        self.label = QtWidgets.QLabel(parent=Calendario)
        self.label.setGeometry(QtCore.QRect(-2, -5, 801, 521))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\Said\\Desktop\\HP QT\\GUI\\../imagen/calendario.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=Calendario)
        self.pushButton.setGeometry(QtCore.QRect(105, 448, 64, 64))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Said\\Desktop\\HP QT\\GUI\\../imagen/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(65, 65))
        self.pushButton.setAutoDefault(True)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.ant = QtWidgets.QPushButton(parent=Calendario)
        self.ant.setGeometry(QtCore.QRect(10, 440, 61, 71))
        self.ant.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ant.setAutoFillBackground(False)
        self.ant.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Said\\Desktop\\HP QT\\GUI\\../imagen/regreso.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ant.setIcon(icon1)
        self.ant.setIconSize(QtCore.QSize(96, 70))
        self.ant.setDefault(False)
        self.ant.setFlat(True)
        self.ant.setObjectName("ant")
        self.sig = QtWidgets.QPushButton(parent=Calendario)
        self.sig.setGeometry(QtCore.QRect(193, 438, 71, 81))
        self.sig.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.sig.setAutoFillBackground(False)
        self.sig.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\Said\\Desktop\\HP QT\\GUI\\../imagen/siguiente.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.sig.setIcon(icon2)
        self.sig.setIconSize(QtCore.QSize(260, 70))
        self.sig.setAutoDefault(True)
        self.sig.setFlat(True)
        self.sig.setObjectName("sig")

        self.retranslateUi(Calendario)
        QtCore.QMetaObject.connectSlotsByName(Calendario)

    def retranslateUi(self, Calendario):
        _translate = QtCore.QCoreApplication.translate
        Calendario.setWindowTitle(_translate("Calendario", "Calendario"))
