# Form implementation generated from reading ui file 'c:\Users\Said\Desktop\HP QT\GUI\Login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        Login.resize(525, 377)
        Login.setStyleSheet("background-color: rgb(53, 151, 97);")
        self.ant = QtWidgets.QPushButton(parent=Login)
        self.ant.setGeometry(QtCore.QRect(10, 300, 51, 71))
        self.ant.setAutoFillBackground(False)
        self.ant.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Said\\Desktop\\HP QT\\GUI\\../imagen/regreso.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ant.setIcon(icon)
        self.ant.setIconSize(QtCore.QSize(250, 60))
        self.ant.setDefault(False)
        self.ant.setFlat(True)
        self.ant.setObjectName("ant")
        self.sig = QtWidgets.QPushButton(parent=Login)
        self.sig.setGeometry(QtCore.QRect(460, 290, 61, 81))
        self.sig.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.sig.setAutoFillBackground(False)
        self.sig.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Said\\Desktop\\HP QT\\GUI\\../imagen/siguiente.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.sig.setIcon(icon1)
        self.sig.setIconSize(QtCore.QSize(250, 60))
        self.sig.setCheckable(True)
        self.sig.setFlat(True)
        self.sig.setObjectName("sig")
        self.ingresar_user = QtWidgets.QLineEdit(parent=Login)
        self.ingresar_user.setGeometry(QtCore.QRect(127, 137, 161, 22))
        self.ingresar_user.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ingresar_user.setObjectName("ingresar_user")
        self.ingresar_passw = QtWidgets.QLineEdit(parent=Login)
        self.ingresar_passw.setGeometry(QtCore.QRect(176, 229, 131, 22))
        self.ingresar_passw.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ingresar_passw.setText("")
        self.ingresar_passw.setDragEnabled(False)
        self.ingresar_passw.setReadOnly(False)
        self.ingresar_passw.setClearButtonEnabled(False)
        self.ingresar_passw.setObjectName("ingresar_passw")
        self.label = QtWidgets.QLabel(parent=Login)
        self.label.setGeometry(QtCore.QRect(0, 0, 531, 381))
        self.label.setStyleSheet("border-radius: 18px;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\Said\\Desktop\\HP QT\\GUI\\../imagen/login.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.ant.raise_()
        self.sig.raise_()
        self.ingresar_user.raise_()
        self.ingresar_passw.raise_()

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.ingresar_user.setPlaceholderText(_translate("Login", "Nombre del usuario"))
        self.ingresar_passw.setPlaceholderText(_translate("Login", "Ingresa contraseña"))
