# Form implementation generated from reading ui file 'c:\Users\Said\Desktop\HP QT\GUI\Pantalla1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Pantalla1(object):
    def setupUi(self, Pantalla1):
        Pantalla1.setObjectName("Pantalla1")
        Pantalla1.resize(529, 297)
        Pantalla1.setStyleSheet("background-color: rgb(169, 255, 129)")
        self.label = QtWidgets.QLabel(parent=Pantalla1)
        self.label.setGeometry(QtCore.QRect(0, 0, 531, 301))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\Said\\Desktop\\HP QT\\GUI\\../imagen/inicio.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.IniSesBtn = QtWidgets.QPushButton(parent=Pantalla1)
        self.IniSesBtn.setGeometry(QtCore.QRect(40, 60, 251, 61))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Said\\Desktop\\HP QT\\GUI\\../imagen/iniciosesbtn.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.IniSesBtn.setIcon(icon)
        self.IniSesBtn.setIconSize(QtCore.QSize(680, 73))
        self.IniSesBtn.setObjectName("IniSesBtn")
        self.RegBtn = QtWidgets.QPushButton(parent=Pantalla1)
        self.RegBtn.setGeometry(QtCore.QRect(40, 160, 251, 61))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Said\\Desktop\\HP QT\\GUI\\../imagen/registro.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.RegBtn.setIcon(icon1)
        self.RegBtn.setIconSize(QtCore.QSize(680, 73))
        self.RegBtn.setObjectName("RegBtn")

        self.retranslateUi(Pantalla1)
        QtCore.QMetaObject.connectSlotsByName(Pantalla1)

    def retranslateUi(self, Pantalla1):
        _translate = QtCore.QCoreApplication.translate
        Pantalla1.setWindowTitle(_translate("Pantalla1", "GJAS: Pantalla1"))
        self.IniSesBtn.setText(_translate("Pantalla1", "n"))
        self.RegBtn.setText(_translate("Pantalla1", "n"))
