# Form implementation generated from reading ui file 'c:\Users\Said\Desktop\HP QT\GUI\Principal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 811, 581))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\Said\\Desktop\\HP QT\\GUI\\../imagen/principal.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.config = QtWidgets.QPushButton(parent=self.centralwidget)
        self.config.setGeometry(QtCore.QRect(680, 280, 75, 24))
        self.config.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.config.setStyleSheet("border-radius:18px;")
        self.config.setAutoDefault(True)
        self.config.setFlat(False)
        self.config.setObjectName("config")
        self.info_perro = QtWidgets.QPushButton(parent=self.centralwidget)
        self.info_perro.setGeometry(QtCore.QRect(70, 70, 291, 51))
        self.info_perro.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.info_perro.setStyleSheet("background-color: rgb(255, 255, 191);")
        self.info_perro.setObjectName("info_perro")
        self.Calendario = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Calendario.setGeometry(QtCore.QRect(70, 460, 301, 51))
        self.Calendario.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Calendario.setStyleSheet("background-color: rgb(255, 255, 191);")
        self.Calendario.setObjectName("Calendario")
        self.Diagnostico = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Diagnostico.setGeometry(QtCore.QRect(70, 340, 301, 51))
        self.Diagnostico.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Diagnostico.setStyleSheet("background-color: rgb(255, 255, 191);")
        self.Diagnostico.setObjectName("Diagnostico")
        self.ctrl_med = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ctrl_med.setEnabled(True)
        self.ctrl_med.setGeometry(QtCore.QRect(68, 200, 301, 51))
        self.ctrl_med.setMinimumSize(QtCore.QSize(189, 0))
        self.ctrl_med.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ctrl_med.setStyleSheet("background-color: rgb(255, 255, 191);")
        self.ctrl_med.setObjectName("ctrl_med")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(506, 33, 244, 229))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("c:\\Users\\Said\\Desktop\\HP QT\\GUI\\../../../Downloads/chihuahua.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.config.setText(_translate("MainWindow", "Ajustes"))
        self.info_perro.setText(_translate("MainWindow", "Sobre mi perro"))
        self.Calendario.setText(_translate("MainWindow", "Calendario"))
        self.Diagnostico.setText(_translate("MainWindow", "Diagnostico"))
        self.ctrl_med.setText(_translate("MainWindow", "Control medico"))
