# Form implementation generated from reading ui file 'c:\Users\Said\Desktop\HP QT\GUI\resultado.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Resultado(object):
    def setupUi(self, Resultado):
        Resultado.setObjectName("Resultado")
        Resultado.resize(802, 501)
        self.label = QtWidgets.QLabel(parent=Resultado)
        self.label.setGeometry(QtCore.QRect(-2, -5, 811, 511))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\Said\\Desktop\\HP QT\\GUI\\../imagen/consulta2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Resultado)
        self.label_2.setGeometry(QtCore.QRect(133, 94, 211, 210))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("c:\\Users\\Said\\Desktop\\HP QT\\GUI\\../../../Downloads/chihuahua.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Resultado)
        self.label_3.setGeometry(QtCore.QRect(550, 320, 101, 20))
        self.label_3.setObjectName("label_3")
        self.continuar = QtWidgets.QPushButton(parent=Resultado)
        self.continuar.setGeometry(QtCore.QRect(524, 340, 151, 51))
        self.continuar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.continuar.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.continuar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Said\\Desktop\\HP QT\\GUI\\../imagen/cont.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.continuar.setIcon(icon)
        self.continuar.setIconSize(QtCore.QSize(200, 200))
        self.continuar.setAutoDefault(True)
        self.continuar.setFlat(True)
        self.continuar.setObjectName("continuar")

        self.retranslateUi(Resultado)
        QtCore.QMetaObject.connectSlotsByName(Resultado)

    def retranslateUi(self, Resultado):
        _translate = QtCore.QCoreApplication.translate
        Resultado.setWindowTitle(_translate("Resultado", "Resultado"))
        self.label_3.setText(_translate("Resultado", "Bien, normal o mal"))
