# Form implementation generated from reading ui file 'c:\Users\Said\Desktop\HP QT\GUI\Sobre_perro.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SobrePerro(object):
    def setupUi(self, SobrePerro):
        SobrePerro.setObjectName("SobrePerro")
        SobrePerro.resize(831, 444)
        self.label = QtWidgets.QLabel(parent=SobrePerro)
        self.label.setGeometry(QtCore.QRect(-2, -5, 831, 451))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\Said\\Desktop\\HP QT\\GUI\\../imagen/sobre.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=SobrePerro)
        self.label_2.setGeometry(QtCore.QRect(264, 33, 541, 241))
        self.label_2.setObjectName("label_2")
        self.verticalScrollBar = QtWidgets.QScrollBar(parent=SobrePerro)
        self.verticalScrollBar.setGeometry(QtCore.QRect(810, 50, 16, 349))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.ant = QtWidgets.QPushButton(parent=SobrePerro)
        self.ant.setGeometry(QtCore.QRect(10, 410, 41, 31))
        self.ant.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ant.setAutoFillBackground(False)
        self.ant.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Said\\Desktop\\HP QT\\GUI\\../imagen/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ant.setIcon(icon)
        self.ant.setIconSize(QtCore.QSize(80, 34))
        self.ant.setDefault(False)
        self.ant.setFlat(True)
        self.ant.setObjectName("ant")

        self.retranslateUi(SobrePerro)
        QtCore.QMetaObject.connectSlotsByName(SobrePerro)

    def retranslateUi(self, SobrePerro):
        _translate = QtCore.QCoreApplication.translate
        SobrePerro.setWindowTitle(_translate("SobrePerro", "Sobre Mi Perro"))
        self.label_2.setText(_translate("SobrePerro", "La raza Chihuahua es una de las razas de perros más pequeñas y antiguas del mundo.\n"
" A continuación, se presentan las características que definen a la raza Chihuahua:\n"
"\n"
"Características físicas\n"
"\n"
"1. Tamaño: Los Chihuahuas son perros muy pequeños, \n"
" con un peso promedio de 1-3 kg (2-6 libras) \n"
"y una altura promedio de 15-23 cm (6-9 pulgadas) en la cruz.\n"
"2. Cabeza: La cabeza del Chihuahua es pequeña, con un cráneo redondeado y un hocico corto y ancho.\n"
"3. Ojos: Los ojos del Chihuahua son grandes y redondos, con una expresión alerta y curiosa.\n"
"4. Orejas: Las orejas del Chihuahua son erectas y triangulares, con una base ancha y una punta afilada.\n"
"5. Cuerpo: El cuerpo del Chihuahua es pequeño y delgado, con un pecho ancho y una cola larga y fina.\n"
" ....."))
